### ISSUE TITLE
Choosing Between Greensock & Mo.js

### ISSUE THREAD

**Issue by Kay2dan** [WebAnimationWorkshops/ama#3]
First of all, love the work on web animation, about time we addressed it properly.

In my app using React & Redux, I am currently using CSS animations & Greensock animations. Love Greensock & how wonderfully it works & is easy to use. Current plan is to strip out CSS animations completely & using Greensock or jumping on Mo.js for all my animation needs for the react app. Mo.js just looks lovely and makes me go all twinkly eyes!

- Do you think Mo.js is mature enough to jump into? 

- Secondly, if you had to choose (& I know how unfair this comparison is given their lifespan), which one of the two would you choose for the react app? They both have their pluses & minuses (e.g. size, old codebase, progression etc)

Thanks,

**Comment by valhead** [comment]
Hi! 
Thanks for participating! 

I think Sarah will have more to add on this, but as much as a love how fun mo.js is and how great it looks, I wouldn't recommend using it in any production projects yet. It doesn't have the robustness that Greensock has at the moment and it's still in beta. So I'd hesitate to use it on any client work or anything on that level.

However, I do think jumping into mo.js for some fun side projects or experiments is a great idea. It has some really interesting features and takes a slightly different approach to animating than Greensock does. Mo.js is just generally really fun to play with. Trying out different libraries will help you get better at animation, even if you decide not to use it in the end.

**Comment by sdras** [comment]
Hi @Kay2dan! 

Thanks for stopping by! 
Yes, I agree with Val that GreenSock is more robust and fully mature. mo.js is so amazing, but is not quite there yet. That said, if you do dive into mo.js + react, there are two ways to go about it- `shouldComponentUpdate: false`: [http://codepen.io/sol0mka/pen/PboNZg/](http://codepen.io/sol0mka/pen/PboNZg/) and a pubsub pattern: [http://codepen.io/sol0mka/pen/GNWKBa?editors=0010](http://codepen.io/sol0mka/pen/GNWKBa?editors=0010). I've found it's a little unwieldy at times with multiple components unless you use the pubsub pattern.

GreenSock has been wonderfully stable in for me in React environments. You can even use something like React-GSAP-Enhancer, though, to be quite honest, I haven't found that I've needed it.

Hope that helps :)

**Comment by Kay2dan** [comment]
Thank you for the wise feedback. I'll stick with `gsap` for now, while keeping a watchful eye over `mo`.
