### ISSUE TITLE
3d feel

### ISSUE THREAD

**Issue by saadkhaan** [WebAnimationWorkshops/ama#6]
Please tell about the best way of faking 2D animation look 3D. Also if you can be generous enough to share 1 or 2 of your animations (ama) tutorials please :)

**Comment by valhead** [comment]
Hi Saad!

Thanks for participating! Faking 3D in 2D usually takes a little trial and error to get right. It depends a lot on what you're animating and what kind of 3D effect you're trying to fake. It's definitely more of an art than science to get it to look right.

Depending on the shape and what kind of 3D rotations you're after, some combination of skew and scale will usually get the job done for faking rotations. When you're going for creating the sense of volume, lining up individual shapes to create the "sides" of an object is the key. (Or this could be entirely in the way the source graphic is drawn.) And for depth, shadows and animating z-index can do the job. (Although you can't animated z-index within an SVG, so a little more creative trickery is required there.) 

For some examples of how to fake 3D in 2D: 
Chris Gannon has a great tutorial on [faking rotation on the x-axis](https://www.youtube.com/watch?v=3Tl81lwianI)
I used skew and blur to fake a y-axis rotation on a triangle character [in this Pen](http://codepen.io/team/WAW/pen/vyMboP)
Sarah has an example of illustrations that create a 3D effect [in this Pen](http://codepen.io/sdras/full/YNpaoJ). 
And David Desandro's CSS transforms has a [nice step-by-step for making a cube with CSS](https://desandro.github.io/3dtransforms/docs/cube.html) 

Hope that helps!

**Comment by saadkhaan** [comment]
Dear Valhead,

Thank you so much for explanations and the links. :)
